//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Basketee.API.PertaminaServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SVC_MS2MobileSoap", Namespace="http://tempuri.org/")]
    public partial class SVC_MS2Mobile : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListLOOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderBBMOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMasterShiftOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReportStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestSendOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestGetMasterShiftOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestGetListLOOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestGetProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestReportStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOrderBBMOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SVC_MS2Mobile() {
            this.Url = global::Basketee.API.Properties.Settings.Default.Pertamina_LPG_API_ServicesLib_PertaminaServices_SVC_MS2Mobile;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendOTPCompletedEventHandler SendOTPCompleted;
        
        /// <remarks/>
        public event GetListLOCompletedEventHandler GetListLOCompleted;
        
        /// <remarks/>
        public event OrderBBMCompletedEventHandler OrderBBMCompleted;
        
        /// <remarks/>
        public event GetMasterShiftCompletedEventHandler GetMasterShiftCompleted;
        
        /// <remarks/>
        public event ReportStockCompletedEventHandler ReportStockCompleted;
        
        /// <remarks/>
        public event GetProductCompletedEventHandler GetProductCompleted;
        
        /// <remarks/>
        public event TestSendOTPCompletedEventHandler TestSendOTPCompleted;
        
        /// <remarks/>
        public event TestGetMasterShiftCompletedEventHandler TestGetMasterShiftCompleted;
        
        /// <remarks/>
        public event TestGetListLOCompletedEventHandler TestGetListLOCompleted;
        
        /// <remarks/>
        public event TestGetProductCompletedEventHandler TestGetProductCompleted;
        
        /// <remarks/>
        public event TestReportStockCompletedEventHandler TestReportStockCompleted;
        
        /// <remarks/>
        public event TestOrderBBMCompletedEventHandler TestOrderBBMCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOTP(string encryptedKey, string strJSON) {
            object[] results = this.Invoke("SendOTP", new object[] {
                        encryptedKey,
                        strJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOTPAsync(string encryptedKey, string strJSON) {
            this.SendOTPAsync(encryptedKey, strJSON, null);
        }
        
        /// <remarks/>
        public void SendOTPAsync(string encryptedKey, string strJSON, object userState) {
            if ((this.SendOTPOperationCompleted == null)) {
                this.SendOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOTPOperationCompleted);
            }
            this.InvokeAsync("SendOTP", new object[] {
                        encryptedKey,
                        strJSON}, this.SendOTPOperationCompleted, userState);
        }
        
        private void OnSendOTPOperationCompleted(object arg) {
            if ((this.SendOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOTPCompleted(this, new SendOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListLO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListLO(string encryptedKey, string strJSON) {
            object[] results = this.Invoke("GetListLO", new object[] {
                        encryptedKey,
                        strJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListLOAsync(string encryptedKey, string strJSON) {
            this.GetListLOAsync(encryptedKey, strJSON, null);
        }
        
        /// <remarks/>
        public void GetListLOAsync(string encryptedKey, string strJSON, object userState) {
            if ((this.GetListLOOperationCompleted == null)) {
                this.GetListLOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListLOOperationCompleted);
            }
            this.InvokeAsync("GetListLO", new object[] {
                        encryptedKey,
                        strJSON}, this.GetListLOOperationCompleted, userState);
        }
        
        private void OnGetListLOOperationCompleted(object arg) {
            if ((this.GetListLOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListLOCompleted(this, new GetListLOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrderBBM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OrderBBM(string encryptedKey, string strJSON) {
            object[] results = this.Invoke("OrderBBM", new object[] {
                        encryptedKey,
                        strJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrderBBMAsync(string encryptedKey, string strJSON) {
            this.OrderBBMAsync(encryptedKey, strJSON, null);
        }
        
        /// <remarks/>
        public void OrderBBMAsync(string encryptedKey, string strJSON, object userState) {
            if ((this.OrderBBMOperationCompleted == null)) {
                this.OrderBBMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderBBMOperationCompleted);
            }
            this.InvokeAsync("OrderBBM", new object[] {
                        encryptedKey,
                        strJSON}, this.OrderBBMOperationCompleted, userState);
        }
        
        private void OnOrderBBMOperationCompleted(object arg) {
            if ((this.OrderBBMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderBBMCompleted(this, new OrderBBMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMasterShift", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMasterShift(string encryptedKey, string strJSON) {
            object[] results = this.Invoke("GetMasterShift", new object[] {
                        encryptedKey,
                        strJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMasterShiftAsync(string encryptedKey, string strJSON) {
            this.GetMasterShiftAsync(encryptedKey, strJSON, null);
        }
        
        /// <remarks/>
        public void GetMasterShiftAsync(string encryptedKey, string strJSON, object userState) {
            if ((this.GetMasterShiftOperationCompleted == null)) {
                this.GetMasterShiftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMasterShiftOperationCompleted);
            }
            this.InvokeAsync("GetMasterShift", new object[] {
                        encryptedKey,
                        strJSON}, this.GetMasterShiftOperationCompleted, userState);
        }
        
        private void OnGetMasterShiftOperationCompleted(object arg) {
            if ((this.GetMasterShiftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMasterShiftCompleted(this, new GetMasterShiftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReportStock(string encryptedKey, string strJSON) {
            object[] results = this.Invoke("ReportStock", new object[] {
                        encryptedKey,
                        strJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReportStockAsync(string encryptedKey, string strJSON) {
            this.ReportStockAsync(encryptedKey, strJSON, null);
        }
        
        /// <remarks/>
        public void ReportStockAsync(string encryptedKey, string strJSON, object userState) {
            if ((this.ReportStockOperationCompleted == null)) {
                this.ReportStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportStockOperationCompleted);
            }
            this.InvokeAsync("ReportStock", new object[] {
                        encryptedKey,
                        strJSON}, this.ReportStockOperationCompleted, userState);
        }
        
        private void OnReportStockOperationCompleted(object arg) {
            if ((this.ReportStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportStockCompleted(this, new ReportStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProduct(string encryptedKey, string strJSON) {
            object[] results = this.Invoke("GetProduct", new object[] {
                        encryptedKey,
                        strJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductAsync(string encryptedKey, string strJSON) {
            this.GetProductAsync(encryptedKey, strJSON, null);
        }
        
        /// <remarks/>
        public void GetProductAsync(string encryptedKey, string strJSON, object userState) {
            if ((this.GetProductOperationCompleted == null)) {
                this.GetProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductOperationCompleted);
            }
            this.InvokeAsync("GetProduct", new object[] {
                        encryptedKey,
                        strJSON}, this.GetProductOperationCompleted, userState);
        }
        
        private void OnGetProductOperationCompleted(object arg) {
            if ((this.GetProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductCompleted(this, new GetProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestSendOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TestEntity TestSendOTP(DataRandomNumber dat) {
            object[] results = this.Invoke("TestSendOTP", new object[] {
                        dat});
            return ((TestEntity)(results[0]));
        }
        
        /// <remarks/>
        public void TestSendOTPAsync(DataRandomNumber dat) {
            this.TestSendOTPAsync(dat, null);
        }
        
        /// <remarks/>
        public void TestSendOTPAsync(DataRandomNumber dat, object userState) {
            if ((this.TestSendOTPOperationCompleted == null)) {
                this.TestSendOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestSendOTPOperationCompleted);
            }
            this.InvokeAsync("TestSendOTP", new object[] {
                        dat}, this.TestSendOTPOperationCompleted, userState);
        }
        
        private void OnTestSendOTPOperationCompleted(object arg) {
            if ((this.TestSendOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestSendOTPCompleted(this, new TestSendOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestGetMasterShift", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TestEntity TestGetMasterShift(GetMasterShift dat) {
            object[] results = this.Invoke("TestGetMasterShift", new object[] {
                        dat});
            return ((TestEntity)(results[0]));
        }
        
        /// <remarks/>
        public void TestGetMasterShiftAsync(GetMasterShift dat) {
            this.TestGetMasterShiftAsync(dat, null);
        }
        
        /// <remarks/>
        public void TestGetMasterShiftAsync(GetMasterShift dat, object userState) {
            if ((this.TestGetMasterShiftOperationCompleted == null)) {
                this.TestGetMasterShiftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestGetMasterShiftOperationCompleted);
            }
            this.InvokeAsync("TestGetMasterShift", new object[] {
                        dat}, this.TestGetMasterShiftOperationCompleted, userState);
        }
        
        private void OnTestGetMasterShiftOperationCompleted(object arg) {
            if ((this.TestGetMasterShiftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestGetMasterShiftCompleted(this, new TestGetMasterShiftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestGetListLO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TestEntity TestGetListLO(DataGetListLo dat) {
            object[] results = this.Invoke("TestGetListLO", new object[] {
                        dat});
            return ((TestEntity)(results[0]));
        }
        
        /// <remarks/>
        public void TestGetListLOAsync(DataGetListLo dat) {
            this.TestGetListLOAsync(dat, null);
        }
        
        /// <remarks/>
        public void TestGetListLOAsync(DataGetListLo dat, object userState) {
            if ((this.TestGetListLOOperationCompleted == null)) {
                this.TestGetListLOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestGetListLOOperationCompleted);
            }
            this.InvokeAsync("TestGetListLO", new object[] {
                        dat}, this.TestGetListLOOperationCompleted, userState);
        }
        
        private void OnTestGetListLOOperationCompleted(object arg) {
            if ((this.TestGetListLOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestGetListLOCompleted(this, new TestGetListLOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestGetProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TestEntity TestGetProduct(DataProduct dat) {
            object[] results = this.Invoke("TestGetProduct", new object[] {
                        dat});
            return ((TestEntity)(results[0]));
        }
        
        /// <remarks/>
        public void TestGetProductAsync(DataProduct dat) {
            this.TestGetProductAsync(dat, null);
        }
        
        /// <remarks/>
        public void TestGetProductAsync(DataProduct dat, object userState) {
            if ((this.TestGetProductOperationCompleted == null)) {
                this.TestGetProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestGetProductOperationCompleted);
            }
            this.InvokeAsync("TestGetProduct", new object[] {
                        dat}, this.TestGetProductOperationCompleted, userState);
        }
        
        private void OnTestGetProductOperationCompleted(object arg) {
            if ((this.TestGetProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestGetProductCompleted(this, new TestGetProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestReportStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TestEntity TestReportStock(ReportStockEntity item) {
            object[] results = this.Invoke("TestReportStock", new object[] {
                        item});
            return ((TestEntity)(results[0]));
        }
        
        /// <remarks/>
        public void TestReportStockAsync(ReportStockEntity item) {
            this.TestReportStockAsync(item, null);
        }
        
        /// <remarks/>
        public void TestReportStockAsync(ReportStockEntity item, object userState) {
            if ((this.TestReportStockOperationCompleted == null)) {
                this.TestReportStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestReportStockOperationCompleted);
            }
            this.InvokeAsync("TestReportStock", new object[] {
                        item}, this.TestReportStockOperationCompleted, userState);
        }
        
        private void OnTestReportStockOperationCompleted(object arg) {
            if ((this.TestReportStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestReportStockCompleted(this, new TestReportStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestOrderBBM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TestEntity TestOrderBBM(OrderBBMEntity item) {
            object[] results = this.Invoke("TestOrderBBM", new object[] {
                        item});
            return ((TestEntity)(results[0]));
        }
        
        /// <remarks/>
        public void TestOrderBBMAsync(OrderBBMEntity item) {
            this.TestOrderBBMAsync(item, null);
        }
        
        /// <remarks/>
        public void TestOrderBBMAsync(OrderBBMEntity item, object userState) {
            if ((this.TestOrderBBMOperationCompleted == null)) {
                this.TestOrderBBMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOrderBBMOperationCompleted);
            }
            this.InvokeAsync("TestOrderBBM", new object[] {
                        item}, this.TestOrderBBMOperationCompleted, userState);
        }
        
        private void OnTestOrderBBMOperationCompleted(object arg) {
            if ((this.TestOrderBBMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestOrderBBMCompleted(this, new TestOrderBBMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DataRandomNumber {
        
        private string noSPBUField;
        
        private string noTelpField;
        
        /// <remarks/>
        public string NoSPBU {
            get {
                return this.noSPBUField;
            }
            set {
                this.noSPBUField = value;
            }
        }
        
        /// <remarks/>
        public string NoTelp {
            get {
                return this.noTelpField;
            }
            set {
                this.noTelpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MaterialShiftLoQty {
        
        private string materialCodeField;
        
        private int shiftField;
        
        private string deliv_NumbField;
        
        private int quantityField;
        
        /// <remarks/>
        public string materialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        public int shift {
            get {
                return this.shiftField;
            }
            set {
                this.shiftField = value;
            }
        }
        
        /// <remarks/>
        public string deliv_Numb {
            get {
                return this.deliv_NumbField;
            }
            set {
                this.deliv_NumbField = value;
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderBBMEntity {
        
        private string noSPBUField;
        
        private string usernameField;
        
        private MaterialStok[] liStokField;
        
        private MaterialShiftLoQty[] liOrderField;
        
        /// <remarks/>
        public string noSPBU {
            get {
                return this.noSPBUField;
            }
            set {
                this.noSPBUField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public MaterialStok[] liStok {
            get {
                return this.liStokField;
            }
            set {
                this.liStokField = value;
            }
        }
        
        /// <remarks/>
        public MaterialShiftLoQty[] liOrder {
            get {
                return this.liOrderField;
            }
            set {
                this.liOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MaterialStok {
        
        private string materialCodeField;
        
        private float stokField;
        
        /// <remarks/>
        public string materialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        public float stok {
            get {
                return this.stokField;
            }
            set {
                this.stokField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReportStockEntity {
        
        private string noSPBUField;
        
        private string usernameField;
        
        private MaterialStok[] liStokField;
        
        /// <remarks/>
        public string noSPBU {
            get {
                return this.noSPBUField;
            }
            set {
                this.noSPBUField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public MaterialStok[] liStok {
            get {
                return this.liStokField;
            }
            set {
                this.liStokField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DataProduct {
        
        private string noSPBUField;
        
        /// <remarks/>
        public string NoSPBU {
            get {
                return this.noSPBUField;
            }
            set {
                this.noSPBUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DataGetListLo {
        
        private string stationNoField;
        
        private string delivenumField;
        
        private string gistatusField;
        
        private string lastUpdateField;
        
        /// <remarks/>
        public string stationNo {
            get {
                return this.stationNoField;
            }
            set {
                this.stationNoField = value;
            }
        }
        
        /// <remarks/>
        public string delivenum {
            get {
                return this.delivenumField;
            }
            set {
                this.delivenumField = value;
            }
        }
        
        /// <remarks/>
        public string gistatus {
            get {
                return this.gistatusField;
            }
            set {
                this.gistatusField = value;
            }
        }
        
        /// <remarks/>
        public string LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMasterShift {
        
        private string stationNoField;
        
        private string materialCodeField;
        
        /// <remarks/>
        public string StationNo {
            get {
                return this.stationNoField;
            }
            set {
                this.stationNoField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TestEntity {
        
        private string encryptedKeyField;
        
        private string strJSONField;
        
        /// <remarks/>
        public string EncryptedKey {
            get {
                return this.encryptedKeyField;
            }
            set {
                this.encryptedKeyField = value;
            }
        }
        
        /// <remarks/>
        public string strJSON {
            get {
                return this.strJSONField;
            }
            set {
                this.strJSONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SendOTPCompletedEventHandler(object sender, SendOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetListLOCompletedEventHandler(object sender, GetListLOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListLOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListLOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void OrderBBMCompletedEventHandler(object sender, OrderBBMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderBBMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderBBMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetMasterShiftCompletedEventHandler(object sender, GetMasterShiftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMasterShiftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMasterShiftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ReportStockCompletedEventHandler(object sender, ReportStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReportStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetProductCompletedEventHandler(object sender, GetProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TestSendOTPCompletedEventHandler(object sender, TestSendOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestSendOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestSendOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TestGetMasterShiftCompletedEventHandler(object sender, TestGetMasterShiftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestGetMasterShiftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestGetMasterShiftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TestGetListLOCompletedEventHandler(object sender, TestGetListLOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestGetListLOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestGetListLOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TestGetProductCompletedEventHandler(object sender, TestGetProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestGetProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestGetProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TestReportStockCompletedEventHandler(object sender, TestReportStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestReportStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestReportStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TestOrderBBMCompletedEventHandler(object sender, TestOrderBBMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestOrderBBMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestOrderBBMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestEntity)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591