//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControl
    {
        public int AccCtrlID { get; set; }
        public short UserTypeID { get; set; }
        public short ModID { get; set; }
        public int FuncID { get; set; }
    
        public virtual MFunctionality MFunctionality { get; set; }
        public virtual MModule MModule { get; set; }
        public virtual MSuperUserType MSuperUserType { get; set; }
    }
}
