//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int ActvID { get; set; }
        public string Item { get; set; }
        public string Activity { get; set; }
        public short SAdminID { get; set; }
        public System.DateTime ActDate { get; set; }
        public System.TimeSpan ActTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual SuperAdmin SuperAdmin { get; set; }
    }
}
