//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public Agency()
        {
            this.AgentAdmins = new HashSet<AgentAdmin>();
            this.AgentBosses = new HashSet<AgentBoss>();
            this.DistributionPoints = new HashSet<DistributionPoint>();
            this.Drivers = new HashSet<Driver>();
            this.InvoiceNumbers = new HashSet<InvoiceNumber>();
        }
    
        public int AgenID { get; set; }
        public string SoldToNumber { get; set; }
        public string AgencyName { get; set; }
        public string Region { get; set; }
        public bool StatusId { get; set; }
        public short CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public short UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int RegionId { get; set; }
    
        public virtual MRegion MRegion { get; set; }
        public virtual SuperAdmin SuperAdmin { get; set; }
        public virtual SuperAdmin SuperAdmin1 { get; set; }
        public virtual ICollection<AgentAdmin> AgentAdmins { get; set; }
        public virtual ICollection<AgentBoss> AgentBosses { get; set; }
        public virtual ICollection<DistributionPoint> DistributionPoints { get; set; }
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual ICollection<InvoiceNumber> InvoiceNumbers { get; set; }
    }
}
