//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerReviewReason
    {
        public ConsumerReviewReason()
        {
            this.ConsumerReviews = new HashSet<ConsumerReview>();
        }
    
        public int ReasonID { get; set; }
        public string ReasonText { get; set; }
    
        public virtual ICollection<ConsumerReview> ConsumerReviews { get; set; }
    }
}
