//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumer
    {
        public Consumer()
        {
            this.ConsumerAddresses = new HashSet<ConsumerAddress>();
            this.ConsumerReviews = new HashSet<ConsumerReview>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ConsID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public string IMEI { get; set; }
        public string AccToken { get; set; }
        public string AppID { get; set; }
        public string AppToken { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool ConsActivated { get; set; }
        public bool ConsBlocked { get; set; }
        public short StatusID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<ConsumerAddress> ConsumerAddresses { get; set; }
        public virtual ICollection<ConsumerReview> ConsumerReviews { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
