//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerAddress
    {
        public ConsumerAddress()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int AddrID { get; set; }
        public int ConsID { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string AdditionalInfo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool IsDefault { get; set; }
        public int StatusID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string RegionName { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
