//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionPoint
    {
        public DistributionPoint()
        {
            this.AgentAdmins = new HashSet<AgentAdmin>();
            this.Drivers = new HashSet<Driver>();
        }
    
        public int DbptID { get; set; }
        public int AgenID { get; set; }
        public string DistributionPointName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Address { get; set; }
        public bool StatusId { get; set; }
        public short CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public short UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual ICollection<AgentAdmin> AgentAdmins { get; set; }
        public virtual SuperAdmin SuperAdmin { get; set; }
        public virtual SuperAdmin SuperAdmin1 { get; set; }
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
