//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverNotificationLog
    {
        public long LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public int NumberOfMessages { get; set; }
    }
}
