//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRegion
    {
        public MRegion()
        {
            this.Agencies = new HashSet<Agency>();
        }
    
        public int RegionID { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
    
        public virtual ICollection<Agency> Agencies { get; set; }
    }
}
