//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public long LogId { get; set; }
        public string ReceiverId { get; set; }
        public string JSONMessage { get; set; }
        public string FCMResponse { get; set; }
    }
}
