//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneTimePwd
    {
        public int OtgID { get; set; }
        public int UserID { get; set; }
        public string UserType { get; set; }
        public string Otg { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
