//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ConsumerReviews = new HashSet<ConsumerReview>();
            this.OrderAllocationLogs = new HashSet<OrderAllocationLog>();
            this.OrderDeliveries = new HashSet<OrderDelivery>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderPrdocuctExchanges = new HashSet<OrderPrdocuctExchange>();
        }
    
        public int OrdrID { get; set; }
        public int ConsID { get; set; }
        public int AddrID { get; set; }
        public Nullable<int> AgadmID { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public short DeliverySlotID { get; set; }
        public int NumberOfProducts { get; set; }
        public decimal SubTotal { get; set; }
        public decimal PromoProduct { get; set; }
        public decimal ShippingCharge { get; set; }
        public decimal PromoShipping { get; set; }
        public decimal GrandTotal { get; set; }
        public short StatusID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> DrvrID { get; set; }
        public decimal RefillSubTotal { get; set; }
        public decimal PromoRefill { get; set; }
        public decimal ExchangeSubTotal { get; set; }
        public decimal PromoExchange { get; set; }
    
        public virtual AgentAdmin AgentAdmin { get; set; }
        public virtual Consumer Consumer { get; set; }
        public virtual ConsumerAddress ConsumerAddress { get; set; }
        public virtual ICollection<ConsumerReview> ConsumerReviews { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual MDeliverySlot MDeliverySlot { get; set; }
        public virtual MOrderStatu MOrderStatu { get; set; }
        public virtual ICollection<OrderAllocationLog> OrderAllocationLogs { get; set; }
        public virtual ICollection<OrderDelivery> OrderDeliveries { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderPrdocuctExchange> OrderPrdocuctExchanges { get; set; }
    }
}
