//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPrdocuctExchange
    {
        public int OrdPrdExID { get; set; }
        public int OrdrID { get; set; }
        public int ProdID { get; set; }
        public string ExchangeWith { get; set; }
        public int ExchangeQuantity { get; set; }
        public decimal ExchangePrice { get; set; }
        public decimal ExchangePromoPrice { get; set; }
        public bool StatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
