//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAllocationLog
    {
        public long AlogID { get; set; }
        public int OrdrID { get; set; }
        public int AgadmID { get; set; }
        public int DbptID { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public bool TimeSlotAvailable { get; set; }
        public short AllocationStatus { get; set; }
        public short AssignmentType { get; set; }
        public short CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
