//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PertaminaLpgDbEntities : DbContext
    {
        public PertaminaLpgDbEntities()
            : base("name=PertaminaLpgDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActivityLog> ActivityLogs { get; set; }
        public DbSet<Agency> Agencies { get; set; }
        public DbSet<AgentAdmin> AgentAdmins { get; set; }
        public DbSet<AgentBoss> AgentBosses { get; set; }
        public DbSet<Consumer> Consumers { get; set; }
        public DbSet<ConsumerAddress> ConsumerAddresses { get; set; }
        public DbSet<ConsumerReview> ConsumerReviews { get; set; }
        public DbSet<ConsumerReviewReason> ConsumerReviewReasons { get; set; }
        public DbSet<ContactInfo> ContactInfoes { get; set; }
        public DbSet<DistributionPoint> DistributionPoints { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<DriverNotificationLog> DriverNotificationLogs { get; set; }
        public DbSet<InvoiceNumber> InvoiceNumbers { get; set; }
        public DbSet<MDeliverySlot> MDeliverySlots { get; set; }
        public DbSet<MDeliveryStatu> MDeliveryStatus { get; set; }
        public DbSet<MFaq> MFaqs { get; set; }
        public DbSet<MFunctionality> MFunctionalities { get; set; }
        public DbSet<MModule> MModules { get; set; }
        public DbSet<MOrderStatu> MOrderStatus { get; set; }
        public DbSet<MRegion> MRegions { get; set; }
        public DbSet<MSuperUserType> MSuperUserTypes { get; set; }
        public DbSet<NotificationLog> NotificationLogs { get; set; }
        public DbSet<OneTimePwd> OneTimePwds { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderAllocationLog> OrderAllocationLogs { get; set; }
        public DbSet<OrderDelivery> OrderDeliveries { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<OrderPrdocuctExchange> OrderPrdocuctExchanges { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductExchange> ProductExchanges { get; set; }
        public DbSet<PromoBanner> PromoBanners { get; set; }
        public DbSet<PromoInfo> PromoInfoes { get; set; }
        public DbSet<Reminder> Reminders { get; set; }
        public DbSet<SuperAdmin> SuperAdmins { get; set; }
        public DbSet<TeleCustomer> TeleCustomers { get; set; }
        public DbSet<TeleOrder> TeleOrders { get; set; }
        public DbSet<TeleOrderDelivery> TeleOrderDeliveries { get; set; }
        public DbSet<TeleOrderDetail> TeleOrderDetails { get; set; }
        public DbSet<TeleOrderPrdocuctExchange> TeleOrderPrdocuctExchanges { get; set; }
        public DbSet<AccessControl> AccessControls { get; set; }
        public DbSet<temp> temps { get; set; }
    
        [EdmFunction("PertaminaLpgDbEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string input, string character)
        {
            var inputParameter = input != null ?
                new ObjectParameter("Input", input) :
                new ObjectParameter("Input", typeof(string));
    
            var characterParameter = character != null ?
                new ObjectParameter("Character", character) :
                new ObjectParameter("Character", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[PertaminaLpgDbEntities].[SplitString](@Input, @Character)", inputParameter, characterParameter);
        }
    
        public virtual int DeleteConsumersByConsumerId(Nullable<int> consID)
        {
            var consIDParameter = consID.HasValue ?
                new ObjectParameter("ConsID", consID) :
                new ObjectParameter("ConsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteConsumersByConsumerId", consIDParameter);
        }
    
        public virtual ObjectResult<GetAgencyDetailsbyOrderIdForSUser_Result> GetAgencyDetailsbyOrderIdForSUser(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgencyDetailsbyOrderIdForSUser_Result>("GetAgencyDetailsbyOrderIdForSUser", orderIdParameter);
        }
    
        public virtual ObjectResult<GetAllDriversForAgentAdmin_Result> GetAllDriversForAgentAdmin(Nullable<int> agent_admin_id)
        {
            var agent_admin_idParameter = agent_admin_id.HasValue ?
                new ObjectParameter("agent_admin_id", agent_admin_id) :
                new ObjectParameter("agent_admin_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDriversForAgentAdmin_Result>("GetAllDriversForAgentAdmin", agent_admin_idParameter);
        }
    
        public virtual ObjectResult<GetAllDriversForTheOrder_Result> GetAllDriversForTheOrder(Nullable<double> cust_lat, Nullable<double> cust_lng)
        {
            var cust_latParameter = cust_lat.HasValue ?
                new ObjectParameter("Cust_lat", cust_lat) :
                new ObjectParameter("Cust_lat", typeof(double));
    
            var cust_lngParameter = cust_lng.HasValue ?
                new ObjectParameter("Cust_lng", cust_lng) :
                new ObjectParameter("Cust_lng", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDriversForTheOrder_Result>("GetAllDriversForTheOrder", cust_latParameter, cust_lngParameter);
        }
    
        public virtual ObjectResult<GetAllOrdersByAgentAdmin_Result> GetAllOrdersByAgentAdmin(Nullable<int> agadmID)
        {
            var agadmIDParameter = agadmID.HasValue ?
                new ObjectParameter("AgadmID", agadmID) :
                new ObjectParameter("AgadmID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrdersByAgentAdmin_Result>("GetAllOrdersByAgentAdmin", agadmIDParameter);
        }
    
        public virtual ObjectResult<GetAllOrdersByAgentBoss_Result> GetAllOrdersByAgentBoss(Nullable<int> abosID)
        {
            var abosIDParameter = abosID.HasValue ?
                new ObjectParameter("AbosID", abosID) :
                new ObjectParameter("AbosID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrdersByAgentBoss_Result>("GetAllOrdersByAgentBoss", abosIDParameter);
        }
    
        public virtual ObjectResult<GetAvailabeDriversForTheOrder_Result> GetAvailabeDriversForTheOrder(Nullable<int> agent_admin_id, Nullable<int> order_id)
        {
            var agent_admin_idParameter = agent_admin_id.HasValue ?
                new ObjectParameter("agent_admin_id", agent_admin_id) :
                new ObjectParameter("agent_admin_id", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("Order_id", order_id) :
                new ObjectParameter("Order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAvailabeDriversForTheOrder_Result>("GetAvailabeDriversForTheOrder", agent_admin_idParameter, order_idParameter);
        }
    
        public virtual ObjectResult<GetDistribution_Result> GetDistribution(Nullable<double> cust_lat, Nullable<double> cust_lng)
        {
            var cust_latParameter = cust_lat.HasValue ?
                new ObjectParameter("Cust_lat", cust_lat) :
                new ObjectParameter("Cust_lat", typeof(double));
    
            var cust_lngParameter = cust_lng.HasValue ?
                new ObjectParameter("Cust_lng", cust_lng) :
                new ObjectParameter("Cust_lng", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDistribution_Result>("GetDistribution", cust_latParameter, cust_lngParameter);
        }
    
        public virtual ObjectResult<GetDriversByAgentBoss_Result> GetDriversByAgentBoss(Nullable<int> abosID)
        {
            var abosIDParameter = abosID.HasValue ?
                new ObjectParameter("AbosID", abosID) :
                new ObjectParameter("AbosID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDriversByAgentBoss_Result>("GetDriversByAgentBoss", abosIDParameter);
        }
    
        public virtual ObjectResult<GetIssuesListForSUser_Result> GetIssuesListForSUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIssuesListForSUser_Result>("GetIssuesListForSUser");
        }
    
        public virtual ObjectResult<GetOrderDeatilsbyOrderIdForSUser_Result> GetOrderDeatilsbyOrderIdForSUser(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderDeatilsbyOrderIdForSUser_Result>("GetOrderDeatilsbyOrderIdForSUser", orderIdParameter);
        }
    
        public virtual ObjectResult<GetOrderList_Result> GetOrderList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderList_Result>("GetOrderList");
        }
    
        public virtual ObjectResult<GetProductDeatilsbyOrderIdForSUser_Result> GetProductDeatilsbyOrderIdForSUser(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDeatilsbyOrderIdForSUser_Result>("GetProductDeatilsbyOrderIdForSUser", orderIdParameter);
        }
    
        public virtual ObjectResult<GetProductsByAgentBoss_Result> GetProductsByAgentBoss(Nullable<int> abosID)
        {
            var abosIDParameter = abosID.HasValue ?
                new ObjectParameter("AbosID", abosID) :
                new ObjectParameter("AbosID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsByAgentBoss_Result>("GetProductsByAgentBoss", abosIDParameter);
        }
    
        public virtual ObjectResult<GetReviewReasonByAgentBoss_Result> GetReviewReasonByAgentBoss(Nullable<int> abosID, Nullable<int> drvrID, Nullable<int> periodType, Nullable<int> periodRange)
        {
            var abosIDParameter = abosID.HasValue ?
                new ObjectParameter("AbosID", abosID) :
                new ObjectParameter("AbosID", typeof(int));
    
            var drvrIDParameter = drvrID.HasValue ?
                new ObjectParameter("DrvrID", drvrID) :
                new ObjectParameter("DrvrID", typeof(int));
    
            var periodTypeParameter = periodType.HasValue ?
                new ObjectParameter("PeriodType", periodType) :
                new ObjectParameter("PeriodType", typeof(int));
    
            var periodRangeParameter = periodRange.HasValue ?
                new ObjectParameter("PeriodRange", periodRange) :
                new ObjectParameter("PeriodRange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReviewReasonByAgentBoss_Result>("GetReviewReasonByAgentBoss", abosIDParameter, drvrIDParameter, periodTypeParameter, periodRangeParameter);
        }
    
        public virtual ObjectResult<GetReviewReasonBySUser_Result> GetReviewReasonBySUser(Nullable<int> sUserId, Nullable<int> agenId, Nullable<int> periodType, Nullable<int> periodRange)
        {
            var sUserIdParameter = sUserId.HasValue ?
                new ObjectParameter("SUserId", sUserId) :
                new ObjectParameter("SUserId", typeof(int));
    
            var agenIdParameter = agenId.HasValue ?
                new ObjectParameter("AgenId", agenId) :
                new ObjectParameter("AgenId", typeof(int));
    
            var periodTypeParameter = periodType.HasValue ?
                new ObjectParameter("PeriodType", periodType) :
                new ObjectParameter("PeriodType", typeof(int));
    
            var periodRangeParameter = periodRange.HasValue ?
                new ObjectParameter("PeriodRange", periodRange) :
                new ObjectParameter("PeriodRange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReviewReasonBySUser_Result>("GetReviewReasonBySUser", sUserIdParameter, agenIdParameter, periodTypeParameter, periodRangeParameter);
        }
    
        public virtual ObjectResult<GetReviewReportByAgentBoss_Result> GetReviewReportByAgentBoss(Nullable<int> abosID, Nullable<int> drvrID, Nullable<int> periodType, Nullable<int> periodRange)
        {
            var abosIDParameter = abosID.HasValue ?
                new ObjectParameter("AbosID", abosID) :
                new ObjectParameter("AbosID", typeof(int));
    
            var drvrIDParameter = drvrID.HasValue ?
                new ObjectParameter("DrvrID", drvrID) :
                new ObjectParameter("DrvrID", typeof(int));
    
            var periodTypeParameter = periodType.HasValue ?
                new ObjectParameter("PeriodType", periodType) :
                new ObjectParameter("PeriodType", typeof(int));
    
            var periodRangeParameter = periodRange.HasValue ?
                new ObjectParameter("PeriodRange", periodRange) :
                new ObjectParameter("PeriodRange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReviewReportByAgentBoss_Result>("GetReviewReportByAgentBoss", abosIDParameter, drvrIDParameter, periodTypeParameter, periodRangeParameter);
        }
    
        public virtual ObjectResult<GetReviewReportBySUser_Result> GetReviewReportBySUser(Nullable<int> suserID, Nullable<int> agenID, Nullable<int> periodType, Nullable<int> periodRange)
        {
            var suserIDParameter = suserID.HasValue ?
                new ObjectParameter("SuserID", suserID) :
                new ObjectParameter("SuserID", typeof(int));
    
            var agenIDParameter = agenID.HasValue ?
                new ObjectParameter("AgenID", agenID) :
                new ObjectParameter("AgenID", typeof(int));
    
            var periodTypeParameter = periodType.HasValue ?
                new ObjectParameter("PeriodType", periodType) :
                new ObjectParameter("PeriodType", typeof(int));
    
            var periodRangeParameter = periodRange.HasValue ?
                new ObjectParameter("PeriodRange", periodRange) :
                new ObjectParameter("PeriodRange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReviewReportBySUser_Result>("GetReviewReportBySUser", suserIDParameter, agenIDParameter, periodTypeParameter, periodRangeParameter);
        }
    
        public virtual ObjectResult<GetSellerReportByAgentBoss_Result> GetSellerReportByAgentBoss(Nullable<int> abosID, Nullable<int> totalType, Nullable<int> periodType, Nullable<int> periodRange, string productIds)
        {
            var abosIDParameter = abosID.HasValue ?
                new ObjectParameter("AbosID", abosID) :
                new ObjectParameter("AbosID", typeof(int));
    
            var totalTypeParameter = totalType.HasValue ?
                new ObjectParameter("TotalType", totalType) :
                new ObjectParameter("TotalType", typeof(int));
    
            var periodTypeParameter = periodType.HasValue ?
                new ObjectParameter("PeriodType", periodType) :
                new ObjectParameter("PeriodType", typeof(int));
    
            var periodRangeParameter = periodRange.HasValue ?
                new ObjectParameter("PeriodRange", periodRange) :
                new ObjectParameter("PeriodRange", typeof(int));
    
            var productIdsParameter = productIds != null ?
                new ObjectParameter("ProductIds", productIds) :
                new ObjectParameter("ProductIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSellerReportByAgentBoss_Result>("GetSellerReportByAgentBoss", abosIDParameter, totalTypeParameter, periodTypeParameter, periodRangeParameter, productIdsParameter);
        }
    
        public virtual ObjectResult<GetSellerReportBySuperAdmin_Result> GetSellerReportBySuperAdmin(Nullable<int> totalType, Nullable<int> periodType, Nullable<int> periodRange, string productIds, string agencyIDs)
        {
            var totalTypeParameter = totalType.HasValue ?
                new ObjectParameter("TotalType", totalType) :
                new ObjectParameter("TotalType", typeof(int));
    
            var periodTypeParameter = periodType.HasValue ?
                new ObjectParameter("PeriodType", periodType) :
                new ObjectParameter("PeriodType", typeof(int));
    
            var periodRangeParameter = periodRange.HasValue ?
                new ObjectParameter("PeriodRange", periodRange) :
                new ObjectParameter("PeriodRange", typeof(int));
    
            var productIdsParameter = productIds != null ?
                new ObjectParameter("ProductIds", productIds) :
                new ObjectParameter("ProductIds", typeof(string));
    
            var agencyIDsParameter = agencyIDs != null ?
                new ObjectParameter("AgencyIDs", agencyIDs) :
                new ObjectParameter("AgencyIDs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSellerReportBySuperAdmin_Result>("GetSellerReportBySuperAdmin", totalTypeParameter, periodTypeParameter, periodRangeParameter, productIdsParameter, agencyIDsParameter);
        }
    
        public virtual ObjectResult<GetSellerReportBySUser_Result> GetSellerReportBySUser(Nullable<int> sUserId, Nullable<int> totalType, Nullable<int> periodType, Nullable<int> periodRange, string productIds, Nullable<int> numOfProducts, Nullable<int> agencyID)
        {
            var sUserIdParameter = sUserId.HasValue ?
                new ObjectParameter("SUserId", sUserId) :
                new ObjectParameter("SUserId", typeof(int));
    
            var totalTypeParameter = totalType.HasValue ?
                new ObjectParameter("TotalType", totalType) :
                new ObjectParameter("TotalType", typeof(int));
    
            var periodTypeParameter = periodType.HasValue ?
                new ObjectParameter("PeriodType", periodType) :
                new ObjectParameter("PeriodType", typeof(int));
    
            var periodRangeParameter = periodRange.HasValue ?
                new ObjectParameter("PeriodRange", periodRange) :
                new ObjectParameter("PeriodRange", typeof(int));
    
            var productIdsParameter = productIds != null ?
                new ObjectParameter("ProductIds", productIds) :
                new ObjectParameter("ProductIds", typeof(string));
    
            var numOfProductsParameter = numOfProducts.HasValue ?
                new ObjectParameter("NumOfProducts", numOfProducts) :
                new ObjectParameter("NumOfProducts", typeof(int));
    
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSellerReportBySUser_Result>("GetSellerReportBySUser", sUserIdParameter, totalTypeParameter, periodTypeParameter, periodRangeParameter, productIdsParameter, numOfProductsParameter, agencyIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetIssuesListCountForSUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetIssuesListCountForSUser");
        }
    
        public virtual ObjectResult<GetSellerRatingBySuperAdmin_Result> GetSellerRatingBySuperAdmin(Nullable<int> periodType, Nullable<int> periodRange, string productIds, string agencyIDs)
        {
            var periodTypeParameter = periodType.HasValue ?
                new ObjectParameter("PeriodType", periodType) :
                new ObjectParameter("PeriodType", typeof(int));
    
            var periodRangeParameter = periodRange.HasValue ?
                new ObjectParameter("PeriodRange", periodRange) :
                new ObjectParameter("PeriodRange", typeof(int));
    
            var productIdsParameter = productIds != null ?
                new ObjectParameter("ProductIds", productIds) :
                new ObjectParameter("ProductIds", typeof(string));
    
            var agencyIDsParameter = agencyIDs != null ?
                new ObjectParameter("AgencyIDs", agencyIDs) :
                new ObjectParameter("AgencyIDs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSellerRatingBySuperAdmin_Result>("GetSellerRatingBySuperAdmin", periodTypeParameter, periodRangeParameter, productIdsParameter, agencyIDsParameter);
        }
    }
}
