//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderPrdocuctExchanges = new HashSet<OrderPrdocuctExchange>();
            this.ProductExchanges = new HashSet<ProductExchange>();
            this.Reminders = new HashSet<Reminder>();
            this.TeleOrderDetails = new HashSet<TeleOrderDetail>();
            this.TeleOrderPrdocuctExchanges = new HashSet<TeleOrderPrdocuctExchange>();
        }
    
        public int ProdID { get; set; }
        public string ProductName { get; set; }
        public int Position { get; set; }
        public string ProductImage { get; set; }
        public string ProductImageDetails { get; set; }
        public decimal TubePrice { get; set; }
        public decimal TubePromoPrice { get; set; }
        public decimal RefillPrice { get; set; }
        public decimal RefillPromoPrice { get; set; }
        public decimal ShippingPrice { get; set; }
        public decimal ShippingPromoPrice { get; set; }
        public bool Published { get; set; }
        public bool StatusId { get; set; }
        public short CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public short UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string ProductCode { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderPrdocuctExchange> OrderPrdocuctExchanges { get; set; }
        public virtual SuperAdmin SuperAdmin { get; set; }
        public virtual SuperAdmin SuperAdmin1 { get; set; }
        public virtual ICollection<ProductExchange> ProductExchanges { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
        public virtual ICollection<TeleOrderDetail> TeleOrderDetails { get; set; }
        public virtual ICollection<TeleOrderPrdocuctExchange> TeleOrderPrdocuctExchanges { get; set; }
    }
}
