//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperAdmin
    {
        public SuperAdmin()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
            this.Agencies = new HashSet<Agency>();
            this.Agencies1 = new HashSet<Agency>();
            this.AgentAdmins = new HashSet<AgentAdmin>();
            this.AgentBosses = new HashSet<AgentBoss>();
            this.ContactInfoes = new HashSet<ContactInfo>();
            this.ContactInfoes1 = new HashSet<ContactInfo>();
            this.DistributionPoints = new HashSet<DistributionPoint>();
            this.DistributionPoints1 = new HashSet<DistributionPoint>();
            this.Drivers = new HashSet<Driver>();
            this.Drivers1 = new HashSet<Driver>();
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
            this.ProductExchanges = new HashSet<ProductExchange>();
            this.ProductExchanges1 = new HashSet<ProductExchange>();
            this.PromoBanners = new HashSet<PromoBanner>();
            this.PromoBanners1 = new HashSet<PromoBanner>();
            this.PromoInfoes = new HashSet<PromoInfo>();
            this.PromoInfoes1 = new HashSet<PromoInfo>();
            this.Reminders = new HashSet<Reminder>();
            this.Reminders1 = new HashSet<Reminder>();
        }
    
        public short SAdminID { get; set; }
        public string FullName { get; set; }
        public string MobileNum { get; set; }
        public string Password { get; set; }
        public string ProfileImage { get; set; }
        public string AppToken { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public short UserTypeID { get; set; }
        public bool StatusID { get; set; }
        public string Email { get; set; }
        public string AccToken { get; set; }
        public string AppID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ICollection<Agency> Agencies { get; set; }
        public virtual ICollection<Agency> Agencies1 { get; set; }
        public virtual ICollection<AgentAdmin> AgentAdmins { get; set; }
        public virtual ICollection<AgentBoss> AgentBosses { get; set; }
        public virtual ICollection<ContactInfo> ContactInfoes { get; set; }
        public virtual ICollection<ContactInfo> ContactInfoes1 { get; set; }
        public virtual ICollection<DistributionPoint> DistributionPoints { get; set; }
        public virtual ICollection<DistributionPoint> DistributionPoints1 { get; set; }
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual ICollection<Driver> Drivers1 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<ProductExchange> ProductExchanges { get; set; }
        public virtual ICollection<ProductExchange> ProductExchanges1 { get; set; }
        public virtual ICollection<PromoBanner> PromoBanners { get; set; }
        public virtual ICollection<PromoBanner> PromoBanners1 { get; set; }
        public virtual ICollection<PromoInfo> PromoInfoes { get; set; }
        public virtual ICollection<PromoInfo> PromoInfoes1 { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
        public virtual ICollection<Reminder> Reminders1 { get; set; }
    }
}
