//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketee.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleOrderDetail
    {
        public int TeleOrdDetID { get; set; }
        public int TeleOrdID { get; set; }
        public int ProdID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> PromoProduct { get; set; }
        public Nullable<decimal> ShippingCharge { get; set; }
        public Nullable<decimal> PromoShipping { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int RefillQuantity { get; set; }
        public decimal RefillPrice { get; set; }
        public decimal PromoRefill { get; set; }
        public decimal RefillSubTotal { get; set; }
        public decimal RefillTotalAmount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TeleOrder TeleOrder { get; set; }
    }
}
